# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('project_date', models.DateField()),
                ('project_image', models.ImageField(upload_to='portfolio/images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
