# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
