# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-20 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimage',
            old_name='title',
            new_name='image',
        ),
    ]
