# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20160420_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
