# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20160424_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
