# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 08:24
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160502_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1500),
        ),
    ]
