# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20160502_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesimage',
            old_name='product',
            new_name='title',
        ),
    ]
