# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayimage',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
