# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 09:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0005_auto_20160508_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayimage',
            old_name='home_background',
            new_name='home_background_display',
        ),
    ]
